[package]
name = "lyrune"
version.workspace = true
edition.workspace = true
publish.workspace = true

[package.metadata.release]
release = true

[dependencies]
anyhow.workspace = true
bytes.workspace = true
directories.workspace = true
futures-util.workspace = true
gpui.workspace = true
gpui-base.workspace = true
gpui-component.workspace = true
gpui-platform.workspace = true
image.workspace = true
keyring.workspace = true
qmc-decrypt.workspace = true
qqmusic-api.workspace = true
quick-xml.workspace = true
reqwest.workspace = true
resvg.workspace = true
rodio.workspace = true
rustls.workspace = true
serde.workspace = true
serde_json.workspace = true
stream-download.workspace = true
tokio.workspace = true
tokio-util.workspace = true
wana_kana.workspace = true
xxhash-rust.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
ashpd.workspace = true
ksni.workspace = true
mpris-server.workspace = true
zbus_systemd.workspace = true

[target.'cfg(any(target_os = "macos", target_os = "windows"))'.dependencies]
tray-icon.workspace = true
